# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
export TERM="rxvt-unicode-256color"

# Path to your oh-my-zsh installation.
export ZSH=~/.config/oh-my-zsh

if [[ -n $DISPLAY ]];
then
    ZSH_THEME="agnoster"
    #ZSH_THEME="powerlevel9k/powerlevel9k"
else
    ZSH_THEME="dieter"
fi

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

plugins=(
    archlinux
    common-aliases
    copyfile
    git
    sudo
    web-search
    wd
    z
)

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
export LANG=fr_FR.UTF-8

# Preferred editor for local and remote sessions
export EDITOR='vim'
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
export SSH_KEY_PATH="~/.ssh/id_ed25519"

source ~/.zsh/agent.sh
source ~/.zsh/aliases.sh

export PATH=$PATH:/home/talos/.local/bin
